version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "8883:1883"
      - "9001:9001"
  #  volumes:
  #    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  #  networks:
  #    - default